service: mi-lambda-demo

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  deploymentBucket:
    name: serverlesszoetechd01
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
